# Generated by Django 5.0.2 on 2024-02-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0004_alter_bagitem_bag_orderitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bagitem',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='bag',
        ),
        migrations.RemoveField(
            model_name='bagitem',
            name='pizza',
        ),
        migrations.DeleteModel(
            name='Bag',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
