# Generated by Django 5.0.2 on 2024-02-15 05:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bag', '0005_remove_bagitem_bag_remove_orderitem_bag_and_more'),
        ('checkout', '0002_remove_order_created_on_remove_order_total_paid_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BagItem',
        ),
    ]
